[project]
name = "polyglot-bot"
version = "0.1.0"
description = "Add your description here"
readme = "docs/README.md"
requires-python = ">=3.11"
dependencies = [
    "colorlog>=6.10.1",
    "discord-py>=2.6.4",
    "openai>=2.11.0",
    "python-dotenv>=1.2.1",
]
